/*
** EPSI PROJECT, 2020
** EPSI_VCHIPS_2020
** File description:
** 4To16DecoderComponent
*/

#include "Utils.hpp"
#include "Component4To16Decoder.hpp"
#include "ComponentFactory.hpp"

vchips::Component4To16Decoder::Component4To16Decoder()
{
    this->setName(std::string("4_to_16_decoder"));
}

std::unique_ptr<vchips::IComponent> vchips::Component4To16Decoder::clone(const std::string &value)
{
    auto component = std::make_unique<vchips::Component4To16Decoder>(*this);
    auto factory = vchips::ComponentFactory::getFactory();
    (void) value;
    component.get()->pins.resize(26);
    auto not_0 = factory->createComponent("not", "");
    auto nand_1 = factory->createComponent("nand", "");
    auto nand_2 = factory->createComponent("nand", "");
    auto nand_3 = factory->createComponent("nand", "");
    auto nand_4 = factory->createComponent("nand", "");
    auto nand_5 = factory->createComponent("nand", "");
    auto nand_6 = factory->createComponent("nand", "");
    auto nand_7 = factory->createComponent("nand", "");
    auto nand_8 = factory->createComponent("nand", "");
    auto nand_3_1 = factory->createComponent("3_nand", "");
    auto nand_3_2 = factory->createComponent("3_nand", "");
    auto nand_3_3 = factory->createComponent("3_nand", "");
    auto nand_3_4 = factory->createComponent("3_nand", "");
    auto nand_3_5 = factory->createComponent("3_nand", "");
    auto nand_3_6 = factory->createComponent("3_nand", "");
    auto nand_3_7 = factory->createComponent("3_nand", "");
    auto nand_3_8 = factory->createComponent("3_nand", "");
    auto nand_3_9 = factory->createComponent("3_nand", "");
    auto nand_3_10 = factory->createComponent("3_nand", "");
    auto nand_3_11 = factory->createComponent("3_nand", "");
    auto nand_3_12 = factory->createComponent("3_nand", "");
    auto nand_3_13 = factory->createComponent("3_nand", "");
    auto nand_3_14 = factory->createComponent("3_nand", "");
    auto nand_3_15 = factory->createComponent("3_nand", "");
    auto nand_3_16 = factory->createComponent("3_nand", "");
    auto not_1 = factory->createComponent("not", "");
    auto not_2 = factory->createComponent("not", "");
    auto not_3 = factory->createComponent("not", "");
    auto not_4 = factory->createComponent("not", "");
    auto not_5 = factory->createComponent("not", "");
    auto not_6 = factory->createComponent("not", "");
    auto not_7 = factory->createComponent("not", "");
    auto not_8 = factory->createComponent("not", "");
    auto not_9 = factory->createComponent("not", "");
    auto not_10 = factory->createComponent("not", "");
    auto not_11 = factory->createComponent("not", "");
    auto not_12 = factory->createComponent("not", "");
    auto not_13 = factory->createComponent("not", "");
    auto not_14 = factory->createComponent("not", "");
    auto not_15 = factory->createComponent("not", "");
    auto not_16 = factory->createComponent("not", "");
    (*component).setLink(9, *not_0, 1);
    (*not_0).setLink(2, *nand_3_1, 3);
    (*not_0).setLink(2, *nand_3_2, 3);
    (*not_0).setLink(2, *nand_3_3, 3);
    (*not_0).setLink(2, *nand_3_4, 3);
    (*not_0).setLink(2, *nand_3_5, 3);
    (*not_0).setLink(2, *nand_3_6, 3);
    (*not_0).setLink(2, *nand_3_7, 3);
    (*not_0).setLink(2, *nand_3_8, 3);
    (*not_0).setLink(2, *nand_3_9, 3);
    (*not_0).setLink(2, *nand_3_10, 3);
    (*not_0).setLink(2, *nand_3_11, 3);
    (*not_0).setLink(2, *nand_3_12, 3);
    (*not_0).setLink(2, *nand_3_13, 3);
    (*not_0).setLink(2, *nand_3_14, 3);
    (*not_0).setLink(2, *nand_3_15, 3);
    (*not_0).setLink(2, *nand_3_16, 3);
    (*nand_3_1).setLink(4, *not_1, 1);
    (*not_1).setLink(2, *component, 10);
    (*nand_3_2).setLink(4, *not_2, 1);
    (*not_2).setLink(2, *component, 11);
    (*nand_3_3).setLink(4, *not_3, 1);
    (*not_3).setLink(2, *component, 12);
    (*nand_3_4).setLink(4, *not_4, 1);
    (*not_4).setLink(2, *component, 13);
    (*nand_3_5).setLink(4, *not_5, 1);
    (*not_5).setLink(2, *component, 14);
    (*nand_3_6).setLink(4, *not_6, 1);
    (*not_6).setLink(2, *component, 15);
    (*nand_3_7).setLink(4, *not_7, 1);
    (*not_7).setLink(2, *component, 16);
    (*nand_3_8).setLink(4, *not_8, 1);
    (*not_8).setLink(2, *component, 17);
    (*nand_3_9).setLink(4, *not_9, 1);
    (*not_9).setLink(2, *component, 18);
    (*nand_3_10).setLink(4, *not_10, 1);
    (*not_10).setLink(2, *component, 19);
    (*nand_3_11).setLink(4, *not_11, 1);
    (*not_11).setLink(2, *component, 20);
    (*nand_3_12).setLink(4, *not_12, 1);
    (*not_12).setLink(2, *component, 21);
    (*nand_3_13).setLink(4, *not_13, 1);
    (*not_13).setLink(2, *component, 22);
    (*nand_3_14).setLink(4, *not_14, 1);
    (*not_14).setLink(2, *component, 23);
    (*nand_3_15).setLink(4, *not_15, 1);
    (*not_15).setLink(2, *component, 24);
    (*nand_3_16).setLink(4, *not_16, 1);
    (*not_16).setLink(2, *component, 25);
    (*component).setLink(1, *nand_1, 1);
    (*component).setLink(1, *nand_3, 1);
    (*component).setLink(2, *nand_2, 1);
    (*component).setLink(2, *nand_4, 1);
    (*component).setLink(3, *nand_1, 2);
    (*component).setLink(3, *nand_2, 2);
    (*component).setLink(4, *nand_3, 2);
    (*component).setLink(4, *nand_4, 2);
    (*component).setLink(5, *nand_5, 2);
    (*component).setLink(5, *nand_7, 1);
    (*component).setLink(6, *nand_6, 1);
    (*component).setLink(6, *nand_8, 1);
    (*component).setLink(7, *nand_5, 1);
    (*component).setLink(7, *nand_6, 2);
    (*component).setLink(8, *nand_7, 2);
    (*component).setLink(8, *nand_8, 2);
    (*nand_1).setLink(3, *nand_3_1, 2);
    (*nand_1).setLink(3, *nand_3_5, 2);
    (*nand_1).setLink(3, *nand_3_9, 2);
    (*nand_1).setLink(3, *nand_3_13, 2);
    (*nand_2).setLink(3, *nand_3_2, 2);
    (*nand_2).setLink(3, *nand_3_6, 2);
    (*nand_2).setLink(3, *nand_3_10, 2);
    (*nand_2).setLink(3, *nand_3_14, 2);
    (*nand_3).setLink(3, *nand_3_3, 2);
    (*nand_3).setLink(3, *nand_3_7, 2);
    (*nand_3).setLink(3, *nand_3_11, 2);
    (*nand_3).setLink(3, *nand_3_15, 2);
    (*nand_4).setLink(3, *nand_3_4, 2);
    (*nand_4).setLink(3, *nand_3_8, 2);
    (*nand_4).setLink(3, *nand_3_12, 2);
    (*nand_4).setLink(3, *nand_3_16, 2);
    (*nand_5).setLink(3, *nand_3_1, 1);
    (*nand_5).setLink(3, *nand_3_2, 1);
    (*nand_5).setLink(3, *nand_3_3, 1);
    (*nand_5).setLink(3, *nand_3_4, 1);
    (*nand_6).setLink(3, *nand_3_5, 1);
    (*nand_6).setLink(3, *nand_3_6, 1);
    (*nand_6).setLink(3, *nand_3_7, 1);
    (*nand_6).setLink(3, *nand_3_8, 1);
    (*nand_7).setLink(3, *nand_3_9, 1);
    (*nand_7).setLink(3, *nand_3_10, 1);
    (*nand_7).setLink(3, *nand_3_11, 1);
    (*nand_7).setLink(3, *nand_3_12, 1);
    (*nand_8).setLink(3, *nand_3_13, 1);
    (*nand_8).setLink(3, *nand_3_14, 1);
    (*nand_8).setLink(3, *nand_3_15, 1);
    (*nand_8).setLink(3, *nand_3_16, 1);
    component.get()->gatesToUpdate.push_back(std::move(not_0));
    component.get()->gatesToUpdate.push_back(std::move(nand_1));
    component.get()->gatesToUpdate.push_back(std::move(nand_2));
    component.get()->gatesToUpdate.push_back(std::move(nand_3));
    component.get()->gatesToUpdate.push_back(std::move(nand_4));
    component.get()->gatesToUpdate.push_back(std::move(nand_5));
    component.get()->gatesToUpdate.push_back(std::move(nand_6));
    component.get()->gatesToUpdate.push_back(std::move(nand_7));
    component.get()->gatesToUpdate.push_back(std::move(nand_8));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_1));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_2));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_3));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_4));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_5));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_6));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_7));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_8));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_9));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_10));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_11));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_12));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_13));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_14));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_15));
    component.get()->gatesToUpdate.push_back(std::move(nand_3_16));
    component.get()->gatesToUpdate.push_back(std::move(not_1));
    component.get()->gatesToUpdate.push_back(std::move(not_2));
    component.get()->gatesToUpdate.push_back(std::move(not_3));
    component.get()->gatesToUpdate.push_back(std::move(not_4));
    component.get()->gatesToUpdate.push_back(std::move(not_5));
    component.get()->gatesToUpdate.push_back(std::move(not_6));
    component.get()->gatesToUpdate.push_back(std::move(not_7));
    component.get()->gatesToUpdate.push_back(std::move(not_8));
    component.get()->gatesToUpdate.push_back(std::move(not_9));
    component.get()->gatesToUpdate.push_back(std::move(not_10));
    component.get()->gatesToUpdate.push_back(std::move(not_11));
    component.get()->gatesToUpdate.push_back(std::move(not_12));
    component.get()->gatesToUpdate.push_back(std::move(not_13));
    component.get()->gatesToUpdate.push_back(std::move(not_14));
    component.get()->gatesToUpdate.push_back(std::move(not_15));
    component.get()->gatesToUpdate.push_back(std::move(not_16));
    return component;
}
